### ISSUE TITLE
Moving to KOT database

### ISSUE THREAD

**Issue by onuratakan** [Naruno/Naruno#1635]
```[tasklist]
### Tasks
- [ ] https://github.com/Naruno/Naruno/issues/1655
- [ ] https://github.com/Naruno/Naruno/issues/1661
- [ ] https://github.com/Naruno/Naruno/issues/1657
- [ ] https://github.com/Naruno/Naruno/issues/1664
- [ ] https://github.com/Naruno/Naruno/issues/1665
- [ ] https://github.com/Naruno/Naruno/issues/1660
- [ ] https://github.com/Naruno/Naruno/issues/1662
- [ ] https://github.com/Naruno/Naruno/issues/1663
- [ ] https://github.com/Naruno/Naruno/issues/1666
- [ ] https://github.com/Naruno/Naruno/issues/1667
- [ ] https://github.com/Naruno/Naruno/issues/1658
- [ ] https://github.com/Naruno/Naruno/issues/1669
- [ ] https://github.com/Naruno/Naruno/issues/1668
- [ ] https://github.com/Naruno/Naruno/issues/1659
```
